version: 2

sources:
  - name: raw
    description: "Raw source data loaded from CSV or external staging"
    tables:
      - name: raw_customer_transactions
        description: "Raw transactional data from sales system"
        columns:
          - name: transaction_id
            tests: [not_null, unique]
          - name: transaction_date
            tests: [not_null]

models:
  - name: stg_customer_transactions
    description: "Staging model that cleans and casts raw customer transactions"
    columns:
      - name: transaction_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: transaction_date
        tests: [not_null]

  - name: dim_customer
    description: "Customer dimension"
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: dim_product
    description: "Product dimension"
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: dim_date
    description: "Date dimension table generated from date range"
    columns:
      - name: date_id
        tests: [not_null, unique]

  - name: fact_customer_transactions
    description: "Fact table capturing transactional measures"
    columns:
      - name: transaction_id
        tests: [not_null, unique]
      - name: total_amount
        tests: [not_null]
